import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs'
import { Toaster } from "sonner";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className='min-h-screen flex flex-col'
        >
          <Toaster position="bottom-left"/>

          <header className="border-b border-b-gray-300 sticky top-0 bg-white z-50">
            <Header />
          </header>

          <div className="bg-[#f4f2ED] flex-1 w-full">
            <main className="max-w-6xl mx-auto">
              {children}
            </main>
          </div>

        </body>
      </html>
    </ClerkProvider>
  );
}
